#!/bin/bash
set -eu
set -o pipefail
#su -c '/sbin/chkconfig --level 345 yum on; /sbin/service yum start'
sed -i 's/upgrade_type = default/upgrade_type = security/g' /etc/dnf/automatic.conf
sed -i 's/emit_via = stdio/emit_via = motd/g' /etc/dnf/automatic.conf
systemctl enable --now dnf-automatic.timer
