#!/bin/bash
set -eu
set -o pipefail
#su -c '/sbin/chkconfig --level 345 yum on; /sbin/service yum start'
#sed -i 's/update_cmd = default/update_cmd = security/g' /etc/yum/yum-cron.conf
#sed -i 's/apply_updates = no/apply_updates = yes/g' /etc/yum/yum-cron.conf
#systemctl restart yum-cron.service
sed -i 's/upgrade_type = default/upgrade_type = security/g' /etc/dnf/automatic.conf
sed -i 's/emit_via = stdio/emit_via = motd/g' /etc/dnf/automatic.conf
#/bin/systemctl enable --now dnf-automatic.timer
#/sbin/service dnf-automatic.timer
